feat: 메인 페이지에서 보여질 글 목록에 대한 데이터를 불러오는 모듈 생성
f-lab-edu/clone-toss-tech pull request #11
Opened 2023-08-31 09:52 UTC by Yoonkeee

## Description

- 해당 모듈은 data/articlesList.json 데이터를 불러와 반환합니다.

![image](https://github.com/f-lab-edu/clone-toss-tech/assets/48908205/a8be0f35-2f8e-402d-9960-8534ac4a08fe)
- 현재 단계는 위 그림에서 Service Worker와 MSW를 합친 수준에 속합니다.

- 해당 모듈은 추후 MSW가 적용될 예정이며, 적용 후 Mock server의 역할을 합니다.
- MSW가 적용되기 전까지는 데이터가 필요한 곳에서 직접 함수를 호출하여 데이터를 받습니다.

## What type of PR is this?

- [x] 🍕 Feature

## Related Tickets & Documents

[Ticket WOO-25](https://linear.app/woody-yoonkee/issue/WOO-25/%EB%A9%94%EC%9D%B8-%ED%8E%98%EC%9D%B4%EC%A7%80%EC%97%90%EC%84%9C-%EB%B3%B4%EC%97%AC%EC%A7%88-%EA%B8%80-%EB%AA%A9%EB%A1%9D%EC%97%90-%EB%8C%80%ED%95%9C-%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%A5%BC-%EB%B6%88%EB%9F%AC%EC%98%A4%EB%8A%94-%EB%AA%A8%EB%93%88-%EC%83%9D%EC%84%B1)

[참고한 글 - (Kakao Tech)Mocking으로 생산성까지 챙기는 FE 개발](https://tech.kakao.com/2021/09/29/mocking-fe/)

2023-08-31 09:53 UTC, Yoonkeee commented on src/api/Requests.js
> +    getArticlesList: data.getArticlesList,
현재 단계에서는 데이터가 필요한 곳에서 직접 함수를 호출하여 데이터를 받습니다.

2023-08-31 09:55 UTC, Yoonkeee commented on src/api/Requests.js
> +      if (!checkDataExist()) {
데이터가 로드되어 있는지 검사합니다.
해당 모듈은 인스턴스로 생성될 때 데이터를 불러오도록 구현하였습니다.
하지만 getArticlesList 함수를 호출했을 때 데이터의 존재 유무 상태를 확인합니다.

2023-08-31 09:56 UTC, Yoonkeee commented on src/api/Requests.js
> +      if (articlesList === undefined) {
데이터가 로드되지 않은 상태라면 한번 더 시도합니다.

2023-08-31 14:18 UTC, Yoonkeee commented on src/api/Requests.js
> +    if (articlesList === undefined) {
데이터가 로드되어 있는지 검사합니다.
해당 모듈은 인스턴스로 생성될 때 데이터를 불러오도록 구현하였습니다.
하지만 getArticlesList 함수를 호출했을 때 데이터의 존재 유무 상태를 확인합니다.

2023-08-31 14:19 UTC, Yoonkeee commented on src/api/Requests.js
> +      await loadData();
데이터가 로드되지 않은 상태라면 한번 더 시도합니다.

2023-09-01 01:43 UTC, f-lab-woody requested changes

2023-09-01 01:43 UTC, f-lab-woody commented on src/api/Requests.js
> +    if (articlesList === undefined) {
설명은 굳이 필요없습니다.
코드를 봤을때 이해가 안된다면 다시 짜면 됩니다.

2023-09-01 01:43 UTC, f-lab-woody commented on src/api/Requests.js
> +      await loadData();
상동

2023-09-01 01:43 UTC, f-lab-woody commented on src/api/Requests.js
> +    getArticlesList: data.getArticlesList,
상동

2023-09-01 01:43 UTC, f-lab-woody commented on src/api/Requests.js
> +async function articlesData() {
해당 펑션은 테스터블한가요?
하나의 펑션이 너무 많은 일을 합니다. -> 테스터블 하지 않습니다.
테스트 코드를 짤 수 있는 단위로 쪼개주시고, 필요한곳에서 사용해주세요.

반복되는 코드가 많은데, 어떻게 줄이면 좋을지 생각해봐주세요.
예) 추상화된 request function 만들고 path 별 적용하기
^이렇게되면 request function 만 테스트해도 많은 테스트코드를 줄일 수 있습니다.

2023-09-01 14:00 UTC, Yoonkeee commented on src/api/Requests.js
> +async function articlesData() {
적용했습니다!

2023-09-01 14:44 UTC, f-lab-woody requested changes
일단 코드의 문제점은 리뷰했습니다.

허나 먼저 워커부터 생성하신 후 모듈적용을하셔야할것같아요.
이렇게 모듈부터 생성하시면, 방향성에 맞춰 코드를 리뷰할 수 없고 그로 인한
수정되는 코드양이 많이집니다.

2023-09-01 14:44 UTC, f-lab-woody commented on src/api/Requests.js
> +import axios from "axios";
파일명을 바꾸는건 어떨까요?

api/Request.js -> abstract function that takes path
api/GetArticleList -> gets articles
api/GetArticle -> gets article

2023-09-01 14:44 UTC, f-lab-woody commented on src/api/Requests.js
> +    alert("Error at Requests.js : " + e);
alert을 하는 이유는뭘까요?
console.err 들어보셨을까요?

추후 env를 분리하여 해당 로그를 보낼지 말지 결정하는 PR을 기대해보겠습니다.

2023-09-01 14:44 UTC, f-lab-woody commented on src/api/Requests.js
> +    return await axios.get(path).then((res) => {
왜 then이 필요할까요?

  try {
    const res = await axios.get(path);
    return res.data;
    ...

2023-09-05 13:06 UTC, closed without merging