chore: 프로젝트 Style Guide 작성
f-lab-edu/clone-toss-tech pull request #14
Opened 2023-09-06 16:02 UTC by Yoonkeee

## Description

- 본 프로젝트의 명명 규칙에 대한 Style Guide를 작성하였습니다.

## What type of PR is this?

- [x] 📝 Documentation Update

## Related Tickets & Documents

Ticket: [WOO-58](https://linear.app/woody-yoonkee/issue/WOO-58/프로젝트에-적용할-스타일-가이드-작성)

2023-09-06 19:31 UTC, f-lab-woody requested changes

2023-09-06 19:31 UTC, f-lab-woody commented on styleguide.md
> +4. 클래스, 생성자, 함수 라이브러리, 단순 객체의 export는 `PascalCase`로 작성합니다.
* 추후 타입스크립트로 변활할때 네이밍인지가 어려울 수 있습니다.
객체 export는 CAPITAL_SNAKE_CASE 로 지정해주세요.

2023-09-06 19:31 UTC, f-lab-woody commented on styleguide.md
> +2. 파일의 이름은 export default의 이름과 일치해야 합니다.
이렇게 하게되면 자기가 만든 룰에 넘어질 수 있어요.
kebab-case를 추천합니다.

2023-09-06 20:13 UTC, Yoonkeee commented on styleguide.md
> +2. 파일의 이름은 export default의 이름과 일치해야 합니다.
수정하였습니다.

2023-09-06 20:13 UTC, Yoonkeee commented on styleguide.md
> +4. 클래스, 생성자, 함수 라이브러리, 단순 객체의 export는 `PascalCase`로 작성합니다.
수정하였습니다.

2023-09-06 22:01 UTC, f-lab-woody requested changes

2023-09-06 22:01 UTC, f-lab-woody commented on styleguide.md
> +4. 클래스, 생성자, 함수 라이브러리의 export는 `PascalCase`로 작성합니다.
함수라이브러리는 export하더라도 camelCase를 사용하는것이 좀더 readable할것 같아요.

2023-09-06 22:01 UTC, f-lab-woody commented on styleguide.md
> +7. 함수의 export default는 `camelCase`로 작성합니다.
클래스, 생성자 함수 등을 exporting 할때 충돌의 여지가 있어보입니다. 
7번 내용은 지우는게 좋겠습니다

2023-09-07 05:51 UTC, Yoonkeee commented on styleguide.md
> +4. 클래스, 생성자, 함수 라이브러리의 export는 `PascalCase`로 작성합니다.
수정하였습니다!

2023-09-07 05:51 UTC, Yoonkeee commented on styleguide.md
> +7. 함수의 export default는 `camelCase`로 작성합니다.
삭제하였습니다!

2023-09-07 12:05 UTC, f-lab-woody approved these changes

2023-09-07 12:05 UTC, f-lab-woody commented on styleguide.md
> +1. 본 프로젝트의 명명
Moving forward: 해당 규칙들 중 적용할만한 코드블럭 예제들을 따로 스타일가이드 내에 정리하는 티켓 생성 및 작업 추후 진행 부탁드립니다.

2023-09-07 12:09 UTC, Yoonkeee commented on styleguide.md
> +1. 본 프로젝트의 명명
Ticket: WOO-60 추후 추가 예정입니다.

2023-09-07 12:45 UTC, merged