chore: 코드 품질과 포맷팅을 위해 ESLint와 Prettier 설치 및 설정
f-lab-edu/clone-toss-tech pull request #15
Opened 2023-09-06 16:48 UTC by Yoonkeee

## Description

- 코드의 품질을 위해 Dev dependencies에 ESLint를 설정하였습니다.
- Airbnb의 Style guide의 규칙들을 설정하기 위해 관련 플러그인들을 설치하였습니다.
- prettier와 ESLint의 충돌을 방지하기 위한 플러그인을 설치하였습니다.

## What type of PR is this?

- [x] 📦 Chore (Release)

## Related Tickets & Documents

Ticket: [WOO-57](https://linear.app/woody-yoonkee/issue/WOO-57/eslint-prettier-airbnb-style-guide-설정)

2023-09-06 17:15 UTC, f-lab-woody requested changes

2023-09-06 17:15 UTC, f-lab-woody commented on package.json
> +}
eof

2023-09-06 17:15 UTC, f-lab-woody commented on package.json
> +  "eslintConfig": {
prettier 는 따로 컨피그파일이 있고, eslint 는 없네요?

별도 eslint config파일로 관리해주세요

2023-09-06 17:15 UTC, f-lab-woody commented on .prettierrc.json
> +    "printWidth": 80,
너무 작은것같아요. 100 - 130으로 설정해주세요

2023-09-06 17:29 UTC, Yoonkeee commented on package.json
> +}
수정하였습니다! 같은 실수 반복해서 죄송합니다!

2023-09-06 17:29 UTC, Yoonkeee commented on package.json
> +  "eslintConfig": {
별도의 파일로 분리하였습니다!

2023-09-06 17:29 UTC, Yoonkeee commented on .prettierrc.json
> +    "printWidth": 80,
130으로 수정하였습니다!

2023-09-06 19:27 UTC, f-lab-woody requested changes

2023-09-06 19:27 UTC, f-lab-woody commented on .eslintrc.json
> +    "import/no-unresolved": "off",
이게 왜 off 죠?

2023-09-06 19:27 UTC, f-lab-woody commented on .eslintrc.json
> +    "no-console": "off"
👀 콘솔로그를 허용하나요?

2023-09-07 10:36 UTC, Yoonkeee commented on .eslintrc.json
> +    "import/no-unresolved": "off",
수정하였습니다.

2023-09-07 10:36 UTC, Yoonkeee commented on .eslintrc.json
> +    "no-console": "off"
수정하였습니다.

2023-09-07 11:59 UTC, f-lab-woody approved these changes

2023-09-07 12:46 UTC, merged