feat: Mock data 응답을 위한 data 세팅, mock server 세팅과 핸들러 생성하기
f-lab-edu/clone-toss-tech pull request #16
Opened 2023-09-08 07:55 UTC by Yoonkeee

## Description

- Mock-up data로 사용될 articles.json, article-list.json을 추가하였습니다.
- Mock server를 구성하였습니다.
- [PR#14 코드 스타일 가이드](https://github.com/f-lab-edu/clone-toss-tech/pull/14)를 적용하여 파일명을 수정하였습니다.

## What type of PR is this?

- [x] 🍕 Feature

## Related Tickets & Documents

Ticket: [WOO-63](https://linear.app/woody-yoonkee/issue/WOO-63/mock-data-응답을-위한-mock-server-worker와-핸들러-생성하기)

2023-09-08 13:04 UTC, f-lab-woody requested changes
리뷰요약
1. 관심사 분리가 안되어 코드를 읽는데 어려움이 생깁니다.
2. html을 리턴하지말고 component를 활용해서 뷰를 그려보시는게 좋겠습니다.

2023-09-08 13:04 UTC, f-lab-woody commented on data/articles.json
> +{
이친구는 왜 필요한거죠?

articles, article-list.json 네이밍에서 혼동이 옵니다. 좀더 나은 네이밍 없나요?

data/ directory이름을 __fixtures__이렇게 바꿔주세요. 보통 테스트용 mock data는 fixtures라는 이름으로 씁니다.

2023-09-08 13:04 UTC, f-lab-woody commented on src/mocks/config.js
> +  rest.get(targetUrl, (req, res, ctx) => res(ctx.status(200), ctx.json(useParams ? data[Object.values(req.params)[0]] : data)));
method는 무조건 get만 받나요?

2023-09-08 13:04 UTC, f-lab-woody commented on src/mocks/config.js
> +  rest.get(targetUrl, (req, res, ctx) => res(ctx.status(200), ctx.json(useParams ? data[Object.values(req.params)[0]] : data)));
useParam을 true로 하드코드한 뒤 param을 안보내면 어떻게 되나요?
개발자의 실수가 발생할 수 있는 세팅입니다.

2023-09-08 13:04 UTC, f-lab-woody commented on src/mocks/config.js
> +  rest.get(targetUrl, (req, res, ctx) => res(ctx.status(200), ctx.json(useParams ? data[Object.values(req.params)[0]] : data)));
콜백을 활용해보는건 어떨까요?

setRequestHandler는 어떤 데이터를 보낼지 몰라야합니다.

2023-09-08 13:04 UTC, f-lab-woody commented on src/mocks/get-article.js
> +import { fetchFile } from './index';
상동 * naming confusion

2023-09-08 13:04 UTC, f-lab-woody commented on src/mocks/index.js
> +    // TODO: .env에서 개발/배포 환경 변수 불러와서 개발일 경우만 콘솔 남기도록 구분할 예정 Ticket WOO-64
Nice

2023-09-08 13:04 UTC, f-lab-woody commented on src/mocks/index.js
> +const initMocks = () => worker.start();
start에서 fail하면 어떻게되죠?

2023-09-08 13:04 UTC, f-lab-woody commented on src/mocks/index.js
> +const articleHandler = setRequestHandler('/api/get/article/:id', articles, true);
관심사를 분리해줬으면 좋겠습니다. 위 내용은 mocks/get-article(*) 로 빼주시는게 좋겠습니다.

2023-09-08 18:11 UTC, Yoonkeee commented on data/articles.json
> +{
article-body.json으로 변경하였습니다.

2023-09-08 18:13 UTC, Yoonkeee commented on src/mocks/config.js
> +  rest.get(targetUrl, (req, res, ctx) => res(ctx.status(200), ctx.json(useParams ? data[Object.values(req.params)[0]] : data)));
1. request method도 함수로 받도록 하였습니다.
2, 3. 조언해주신대로 콜백으로 추상화하였습니다.

2023-09-08 18:13 UTC, Yoonkeee commented on src/mocks/index.js
> +const initMocks = () => worker.start();
try, catch를 추가하였습니다.

2023-09-08 18:14 UTC, Yoonkeee commented on src/mocks/index.js
> +const articleHandler = setRequestHandler('/api/get/article/:id', articles, true);
데이터를 불러오고 핸들러를 설정하는 부분을 각 파일로 분리하였습니다.

2023-09-08 18:14 UTC, Yoonkeee commented on src/mocks/get-article.js
> +import { fetchFile } from './index';
get-article-body.js로 변경하였습니다.

2023-09-09 21:14 UTC, f-lab-woody requested changes
> 본문 내용을 컴포넌트로 그리는 부분 구상하고 추후 적용하도록 하겠습니다!

^고민이후에 진행하시거나 article-body.json은 빼고 작업해야하지 않을까요?

2023-09-09 21:14 UTC, f-lab-woody commented on src/mocks/index.js
> +export async function fetchFile(path) {
mocks/ index.js에선 없었으면 합니다.

해당펑션 다른 파일(utils)로 옮기신 후 테스트코드 작성해주세요.

2023-09-09 21:14 UTC, f-lab-woody commented on src/mocks/index.js
> +export async function fetchFile(path) {
그냥 mock data를 불러오는건데 axios를 굳이 쓸 필요가 있나요?

2023-09-09 21:14 UTC, f-lab-woody commented on src/mocks/index.js
> +export async function fetchFile(path) {
데이터를 fixture디렉토리에서 불러온 후 내보내주기만 하면 되지 않을까요?

예) 
if path === 'xyz' return () => ARTICLE_LIST;
if path === 'xyz/:id' return (id) => ARTICLE_DETAIL.find((d) => d.id === id);

2023-09-09 21:14 UTC, f-lab-woody commented on src/mocks/index.js
> +    // TODO: Same as below. Ticket WOO-64
보통 중복되는 코멘트를 위에 적어두고 아래에서 상동 이라고 합니다.

2023-09-09 21:14 UTC, f-lab-woody commented on src/mocks/index.js
> +const articleListHandler = await getArticleListHandler();
async function으로 감싸줘야하지 않나요?

2023-09-09 21:14 UTC, f-lab-woody commented on src/mocks/index.js
> +const worker = setupWorker(...handlers);
6-11번 줄 모두 initMocks에 들어가는게 좋겠습니다

2023-09-09 21:14 UTC, f-lab-woody commented on src/mocks/config.js
> +const setRequestHandler = (requestMethod, targetUrl, data, callback) =>
이름이 가독성이 엄청 떨어집니다.
결국 해당 펑션이 하는건 서버와 같지 않나요? 

createMockServerEndpoint 정도는 어떨까요?

2023-09-09 21:14 UTC, f-lab-woody commented on src/mocks/config.js
> +  requestMethod(targetUrl, (req, res, ctx) => res(ctx.status(200), ctx.json(callback(req, data))));
requestMethod보단 method가 좀더 간결할 것같아요.

2023-09-09 21:14 UTC, f-lab-woody commented on src/mocks/get-article-body.js
> +  return setRequestHandler(rest.get, '/api/get/article/:id', fixture, (req, data) => data[req.params.id]);
api endpoint를 만드는데 있어 메서드를 넣는건 좋지 않은 방식입니다.

https://blog.dreamfactory.com/best-practices-for-naming-rest-api-endpoints/#:~:text=Use%20nouns%2C%20preferably%20plural%2C%20to,use%20file%20extensions%20in%20URIs.

2023-09-09 21:14 UTC, f-lab-woody commented on src/mocks/get-article-list.js
> +  return setRequestHandler(rest.get, '/api/get/article-list', fixture, (req, data) => data);
상동

2023-09-09 21:14 UTC, f-lab-woody commented on src/mocks/index.js
> +const handlers = [articleListHandler, articleBodyHandler];
좀더 간결하게 만들 수 있을것같아요

2023-09-10 15:19 UTC, f-lab-woody commented on src/mocks/index.js
> +    const worker = setupWorker(getArticleListHandler());
const mockHandlers = [getArticleListHandler, xyz..].map((handler)=> handler());
setupWorkder(...mockHandlers);

2023-09-10 15:37 UTC, f-lab-woody commented on src/mocks/get-article-list.js
> +  return createMockServerEndpoint(rest.get, '/api/article-list', fetchFile('article-list'), (req, data) => data);
`/api/article-list` -> `/articles' 가 적당할 것같아요.

2023-09-10 15:39 UTC, f-lab-woody commented on src/mocks/get-article-list.js
> +  return createMockServerEndpoint(rest.get, '/api/article-list', fetchFile('article-list'), (req, data) => data);
endpoint에 api가 계속 붙는다면 위쪽 config에서 prefiex를 고정으로 걸어둬도 좋겠습니다.

basePath = '/api/'

`${basePath}${targetUrl}`

2023-09-10 15:48 UTC, Yoonkeee commented on src/mocks/config.js
> +const setRequestHandler = (requestMethod, targetUrl, data, callback) =>
수정하였습니다!

2023-09-10 15:48 UTC, Yoonkeee commented on src/mocks/config.js
> +  requestMethod(targetUrl, (req, res, ctx) => res(ctx.status(200), ctx.json(callback(req, data))));
수정하였습니다!

2023-09-10 15:48 UTC, Yoonkeee commented on src/mocks/get-article-body.js
> +  return setRequestHandler(rest.get, '/api/get/article/:id', fixture, (req, data) => data[req.params.id]);
수정하였습니다!

2023-09-10 15:48 UTC, Yoonkeee commented on src/mocks/get-article-list.js
> +  return setRequestHandler(rest.get, '/api/get/article-list', fixture, (req, data) => data);
수정하였습니다!

2023-09-10 15:48 UTC, Yoonkeee commented on src/mocks/index.js
> +const articleListHandler = await getArticleListHandler();
더 간결하게 수정하였습니다!

2023-09-10 15:48 UTC, Yoonkeee commented on src/mocks/index.js
> +const handlers = [articleListHandler, articleBodyHandler];
더 간결하게 수정하였습니다!

2023-09-10 15:48 UTC, Yoonkeee commented on src/mocks/index.js
> +    // TODO: Same as below. Ticket WOO-64
수정하였습니다!

2023-09-10 15:48 UTC, Yoonkeee commented on src/mocks/index.js
> +const worker = setupWorker(...handlers);
더 간결하게 수정하였습니다!

2023-09-10 15:48 UTC, Yoonkeee commented on src/mocks/index.js
> +export async function fetchFile(path) {
수정하였습니다!

2023-09-10 17:42 UTC, Yoonkeee commented on src/mocks/index.js
> +    const worker = setupWorker(getArticleListHandler());
수정하였습니다!

2023-09-10 17:42 UTC, Yoonkeee commented on src/mocks/get-article-list.js
> +  return createMockServerEndpoint(rest.get, '/api/article-list', fetchFile('article-list'), (req, data) => data);
수정하였습니다!

2023-09-10 19:42 UTC, f-lab-woody approved these changes
LGTM

2023-09-11 01:55 UTC, merged