feat: 데이터를 불러오기 위한 api 추가
f-lab-edu/clone-toss-tech pull request #18
Opened 2023-09-11 02:38 UTC by Yoonkeee

## Description

- 데이터를 불러오기 위한 api를 추가하였습니다.

## What type of PR is this?

- [x] 🍕 Feature

## Related Tickets & Documents

[Ticket: WOO-66](https://linear.app/woody-yoonkee/issue/WOO-66/데이터를-불러오기-위한-api-추가)

2023-09-11 12:43 UTC, f-lab-woody requested changes

2023-09-11 12:43 UTC, f-lab-woody commented on src/api/get-article-body.js
> +import { fetchData } from './index';
불필요해보입니다.

2023-09-11 12:43 UTC, f-lab-woody commented on src/api/get-article-list.js
> +import { fetchData } from './index';
상동

2023-09-11 12:43 UTC, f-lab-woody commented on src/api/index.js
> +    const res = await instance.get(path);
fetchData = (path) => {
try{
return instance.get(path);
} catch(e){
console.error()
}

const {data} = fetchData('article-list');

2023-09-13 13:05 UTC, Yoonkeee commented on src/api/get-article-body.js
> +import { fetchData } from './index';
파일 삭제하였습니다.

2023-09-13 13:05 UTC, Yoonkeee commented on src/api/get-article-list.js
> +import { fetchData } from './index';
파일 삭제하였습니다.

2023-09-13 13:05 UTC, Yoonkeee commented on src/api/index.js
> +    const res = await instance.get(path);
수정하였습니다.

2023-09-13 14:28 UTC, f-lab-woody approved these changes

2023-09-13 14:29 UTC, merged