feat: 개발 환경에서만 console.error 남기도록 수정 및 환경 파일 추가
f-lab-edu/clone-toss-tech pull request #20
Opened 2023-09-13 14:45 UTC by Yoonkeee

## Description

- .env.production 파일에는 배포 환경에서 사용될 변수가 있습니다.
- 앱은 개발 환경 혹은 배포 환경의 환경 변수를 런타임에서 동적으로 받습니다.

## What type of PR is this?

- [x] 🍕 Feature

## Related Tickets & Documents

[Ticket: WOO-64](https://linear.app/woody-yoonkee/issue/WOO-64/console-error를-표기하기-위한-개발배포-환경-구분-추가)

2023-09-14 02:33 UTC, f-lab-woody commented on src/api/index.js
> +    if (import.meta.env.VITE_APP_ENV === 'development') {
https://vitejs.dev/guide/env-and-mode.html#env-variables

builtin env variable이 있지 않나요?

2023-09-14 08:24 UTC, Yoonkeee commented on src/api/index.js
> +    if (import.meta.env.VITE_APP_ENV === 'development') {
수정하였습니다!

2023-09-15 01:13 UTC, f-lab-woody requested changes
<img width="651" alt="image" src="https://github.com/f-lab-edu/clone-toss-tech/assets/132863642/2decafed-300c-4870-bc1d-71375c3fe574">
문서한번 다시 읽어봐주세요

2023-09-15 03:41 UTC, f-lab-woody approved these changes

2023-09-15 06:23 UTC, merged