feat: 앱에서 데이터를 다루기 위해 model.js를 생성하고 index.html에 연결
f-lab-edu/clone-toss-tech pull request #22
Opened 2023-09-15 18:11 UTC by Yoonkeee

## Description

- app.js에서 mock server를 init합니다.
- model 인스턴스를 생성합니다.
- model로부터 메인 페이지에서 사용될 전체 article 데이터를 받을 수 있습니다.
- model로부터 본문 페이지에서 사용될 article 데이터를 받을 수 있습니다.

## What type of PR is this?

- [x] 🍕 Feature

## Related Tickets & Documents

[Ticket: WOO-71](https://linear.app/woody-yoonkee/issue/WOO-71/앱에서-데이터를-다루기-위해-modeljs를-생성하고-indexhtml에-연결)

2023-09-16 04:44 UTC, f-lab-woody requested changes

2023-09-16 04:44 UTC, f-lab-woody commented on src/model.js
> +export default class Model {
위 모델은 테스트하기가 어려워보입니다.

어떻게 해보면 좋을까요?

2023-09-19 04:16 UTC, f-lab-woody requested changes

2023-09-19 04:16 UTC, f-lab-woody commented on src/app.js
> +import { initMocks } from './mocks/index';
임포트하셨으면 사용하셔야해요

2023-09-19 04:16 UTC, f-lab-woody commented on __fixtures__/article-list.json
>        "title": "레고처럼 조립하는 토스 앱",
보통 fixture data수정은 다른 pr에서 진행합니다

2023-09-19 04:16 UTC, f-lab-woody commented on src/data-handler.js
> +import { fetchData } from './api/index.js';
bad naming

2023-09-19 04:16 UTC, f-lab-woody commented on src/data-handler.js
> +export default class DataHandler {
디렉토리 따로 설정 해주세요

2023-09-19 04:16 UTC, f-lab-woody commented on src/data-handler.js
> +export default class DataHandler {
이름은 데이터 핸들러인데, 결국 하는건 아티클 데이터를 핸들링하네요?
이름이 이대로 괜찮나요?

2023-09-19 13:06 UTC, f-lab-woody commented on src/data-handler.js
> +export default class DataHandler {
/models/index.js, article.js

import {article} from '/models'

2023-09-19 16:39 UTC, Yoonkeee commented on __fixtures__/article-list.json
>        "title": "레고처럼 조립하는 토스 앱",
제거하였습니다.

2023-09-19 16:39 UTC, Yoonkeee commented on src/data-handler.js
> +import { fetchData } from './api/index.js';
수정하였습니다.

2023-09-19 16:39 UTC, Yoonkeee commented on src/data-handler.js
> +export default class DataHandler {
수정하였습니다.

2023-09-20 00:03 UTC, f-lab-woody requested changes

2023-09-20 00:03 UTC, f-lab-woody commented on src/app.js
> +initMocks();
만약 이게 fail하면 어떻게 되죠?

2023-09-20 00:03 UTC, f-lab-woody commented on src/models/article.js
> +const makeRequestToApi = path => {
API는 대문자로 써주세요

2023-09-20 00:03 UTC, f-lab-woody commented on src/models/article.js
> +      ...this.articleList.articles[id],
articleList 안쪽 articles가 있는건가요?

차라리 처음 set해줄때 articles를 빼서 해주는건 어때요?

list라고 표현해놓고 실제로는 object형태라서 헷갈립니다.

2023-09-20 00:03 UTC, f-lab-woody commented on src/app.js
> +initMocks();
dom api를 활용해서 완전히 로드되었는지 확인후 콜백으로 넣어주는건 어떨까요?
```javascript
const start = () => {
//initMocks 내 return을 true or false로 변경해서 실제 사용할땐

const hasMocks = initMocks();

if (hasMocks) {
 const app = ...
} 
}

dom API.('', start);

```

2023-09-20 10:55 UTC, Yoonkeee commented on src/models/article.js
> +      ...this.articleList.articles[id],
수정했습니다!

2023-09-20 10:55 UTC, Yoonkeee commented on src/models/article.js
> +const makeRequestToApi = path => {
수정했습니다!

2023-09-20 11:53 UTC, f-lab-woody commented on src/models/article.js
> +  const result = await makeRequestToAPI('/articles');
if (result){
...
}

it (!result) return null;

...

2023-09-20 15:04 UTC, Yoonkeee commented on src/models/article.js
> +  const result = await makeRequestToAPI('/articles');
수정했습니다!

2023-09-20 15:04 UTC, Yoonkeee commented on src/app.js
> +initMocks();
수정했습니다!

2023-09-20 15:19 UTC, f-lab-woody requested changes

2023-09-20 15:19 UTC, f-lab-woody commented on src/models/article.js
> +const makeRequestToAPI = path => {
nit, makeRequest가 더 좋아보입니다

2023-09-20 15:19 UTC, f-lab-woody commented on src/models/article.js
> +    const body = await makeRequestToAPI(`/article/${id}`);
try catch 는 어디있죠?

2023-09-20 15:19 UTC, f-lab-woody commented on src/models/article.js
> +    const body = await makeRequestToAPI(`/article/${id}`);
const {data} = await makeRequestToAPI(`/article/${id}`);

2023-09-20 15:19 UTC, f-lab-woody commented on src/app.js
> +          <div class="logo-image" id="logo-image">
저번부터 궁금했는데, 왜 아이디와 클래스를 동일한 이름으로 처리하나요?

2023-09-20 15:19 UTC, f-lab-woody commented on src/app.js
> +          <div class="logo-image" id="logo-image">
두개가 필요한 이유가 있나요?

2023-09-20 15:19 UTC, f-lab-woody commented on src/app.js
> +          <div class="logo-image" id="logo-image">
CSS작성시 헷갈릴것같아요

2023-09-20 16:28 UTC, Yoonkeee commented on src/models/article.js
> +const makeRequestToAPI = path => {
수정하였습니다!

2023-09-20 16:32 UTC, Yoonkeee commented on src/models/article.js
> +    const body = await makeRequestToAPI(`/article/${id}`);
추가하였습니다!

2023-09-20 16:32 UTC, Yoonkeee commented on src/app.js
> +          <div class="logo-image" id="logo-image">
제거하였습니다!

2023-09-20 23:44 UTC, f-lab-woody approved these changes
코멘트가 있지만 있지만 마이너해서 approve!

2023-09-20 23:44 UTC, f-lab-woody commented on src/app.js
> +      <div class="content" id="content"></div>
.content#content?

2023-09-20 23:44 UTC, f-lab-woody commented on src/models/article.js
> +  if (!result) return null;
nit,return 다음에 또다른 로직이 있는경운 엠티라인이 읽기 편합니다

2023-09-20 23:44 UTC, f-lab-woody commented on src/models/article.js
> +    // TODO: DEV 환경일 때 에러 정보 로그를 출력하는 Util function 추가 예정 Ticket: WOO-75
이것 계속 가져가나요?

2023-09-20 23:44 UTC, f-lab-woody commented on src/models/article.js
> +      // TODO: 상동 Ticket: WOO-75
상동

2023-09-21 08:59 UTC, merged