feat: 메인 페이지 렌더를 위한 함수 구현
f-lab-edu/clone-toss-tech pull request #23
Opened 2023-09-19 02:11 UTC by Yoonkeee

## Description

- 메인 페이지의 아티클 리스트를 렌더하는 함수입니다.
- 작성일을 표현하기 위해 날짜 포맷팅을 하는 util 함수를 추가하였습니다.

## What type of PR is this?

- [x] 🍕 Feature

## Related Tickets & Documents

[Ticket: WOO-72](https://linear.app/woody-yoonkee/issue/WOO-72/main-view-생성)

2023-09-19 04:22 UTC, f-lab-woody requested changes

2023-09-19 04:22 UTC, f-lab-woody commented on src/utils.js
> +export function formatDate(inputDate) {
date fns를 사용하시는걸 추천드립니다

2023-09-19 04:22 UTC, f-lab-woody commented on src/views/main/index.js
> +  const articleListArray = Object.entries(articleList).map(([id, value]) => ({ id, ...value }));
articleListArray? 

articles가 적당할것같아요.

2023-09-19 04:22 UTC, f-lab-woody commented on src/views/main/index.js
> +  $articles.appendChild(newArticlesUlElement);
반복문이 이렇게나 많이 나올필요가 있나요?

좀더 간단하게 만들 수 있을것같아요.

2023-09-19 16:07 UTC, Yoonkeee commented on src/utils.js
> +export function formatDate(inputDate) {
수정하였습니다!

2023-09-19 16:07 UTC, Yoonkeee commented on src/views/main/index.js
> +  const articleListArray = Object.entries(articleList).map(([id, value]) => ({ id, ...value }));
수정하였습니다!

2023-09-19 16:07 UTC, Yoonkeee commented on src/views/main/index.js
> +  $articles.appendChild(newArticlesUlElement);
수정하였습니다!

2023-09-20 00:13 UTC, f-lab-woody requested changes

2023-09-20 00:13 UTC, f-lab-woody commented on src/utils.js
> +  format(new Date(`${inputDate.substring(0, 4)}.${inputDate.substring(4, 6)}.${inputDate.substring(6, 8)}`), 'yyyy.MM.dd');
parseISO를활용해보시는건 어떠세요?

2023-09-20 00:13 UTC, f-lab-woody commented on src/utils.js
> +  format(new Date(`${inputDate.substring(0, 4)}.${inputDate.substring(4, 6)}.${inputDate.substring(6, 8)}`), 'yyyy.MM.dd');
https://date-fns.org/v2.30.0/docs/parseISO

2023-09-20 00:13 UTC, f-lab-woody commented on src/views/main/index.js
> +  const newArticlesUlElement = document.createElement('ul');
변수명을 그냥 ul하면 안되나요?

2023-09-20 00:13 UTC, f-lab-woody commented on src/views/main/index.js
> +  const article = document.createElement('div');
왜 div인가요?

ul이면 li 나 ol을 사용해야할텐데 특별한 이유가 있나요?

2023-09-20 00:13 UTC, f-lab-woody commented on src/views/main/index.js
> +  const { thumbnail_image: thumbnailImage, title, summary, created_date: createdDate, id } = props;
alpha

2023-09-20 00:13 UTC, f-lab-woody commented on src/views/main/index.js
> +  document.getElementById('articles').appendChild(newArticlesUlElement);
articleList가 undefined일경우 어떻게 되나요?

예외처리는 어디있죠?

2023-09-20 01:57 UTC, f-lab-woody commented on src/views/main/index.js
> +    newArticlesUlElement.prepend(makeArticleElement({ id, ...value }));
value말고 content라는 표현이 더 좋겠네요

2023-09-20 09:38 UTC, Yoonkeee commented on src/utils.js
> +  format(new Date(`${inputDate.substring(0, 4)}.${inputDate.substring(4, 6)}.${inputDate.substring(6, 8)}`), 'yyyy.MM.dd');
수정하였습니다!

2023-09-20 09:38 UTC, Yoonkeee commented on src/views/main/index.js
> +  const article = document.createElement('div');
수정하였습니다!

2023-09-20 09:38 UTC, Yoonkeee commented on src/views/main/index.js
> +  const { thumbnail_image: thumbnailImage, title, summary, created_date: createdDate, id } = props;
수정하였습니다!

2023-09-20 09:38 UTC, Yoonkeee commented on src/views/main/index.js
> +  document.getElementById('articles').appendChild(newArticlesUlElement);
추가하였습니다!

2023-09-20 09:39 UTC, Yoonkeee commented on src/views/main/index.js
> +    newArticlesUlElement.prepend(makeArticleElement({ id, ...value }));
수정하였습니다!

2023-09-20 09:39 UTC, Yoonkeee commented on src/views/main/index.js
> +  const newArticlesUlElement = document.createElement('ul');
수정하였습니다!

2023-09-20 11:59 UTC, f-lab-woody commented on src/views/main/index.js
> +export default function render(articleList) {
const articleContainer = document.getElementById('articles');
const errorComponent = documenmt.createElemtn();

if(!articleList) return articlesContainer.appendChild(errorComponent);

2023-09-20 11:59 UTC, f-lab-woody commented on src/views/main/index.js
> +      <span>${title}</span>
class 필요없나요?

2023-09-20 15:12 UTC, Yoonkeee commented on src/views/main/index.js
> +export default function render(articleList) {
수정했습니다!

2023-09-20 15:12 UTC, Yoonkeee commented on src/views/main/index.js
> +      <span>${title}</span>
수정했습니다!

2023-09-20 15:23 UTC, f-lab-woody requested changes

2023-09-20 15:23 UTC, f-lab-woody commented on src/views/error/index.js
> +const ErrorComponent = () => {
nit, 추후 어떻게하면 더 좋은 컴포넌트를 만들수 있을지 고민해봐요

2023-09-20 15:23 UTC, f-lab-woody commented on src/views/main/index.js
> +
여기 newline은 왜있는건가요?

2023-09-20 15:23 UTC, f-lab-woody commented on src/views/main/index.js
> +  if (!articleList) {
굳이 스코프를 따로 줄 필요가 있었나요?

if() return ...;

2023-09-20 15:23 UTC, f-lab-woody commented on src/views/main/index.module.css
> +.main-title {
저는 css 파일을 만들라고 말씀드리진 않았습니다

2023-09-20 16:32 UTC, Yoonkeee commented on src/views/error/index.js
> +const ErrorComponent = () => {
에러 내용을 넣을 수 있도록 개선했습니다!

2023-09-20 16:33 UTC, Yoonkeee commented on src/views/main/index.js
> +
제거했습니다!

2023-09-20 16:33 UTC, Yoonkeee commented on src/views/main/index.js
> +  if (!articleList) {
수정했습니다!

2023-09-20 16:33 UTC, Yoonkeee commented on src/views/main/index.module.css
> +.main-title {
제거했습니다!

2023-09-20 23:47 UTC, f-lab-woody requested changes

2023-09-20 23:47 UTC, f-lab-woody commented on src/views/error/index.js
> +const ErrorComponent = errorMessage => {
nice

2023-09-20 23:47 UTC, f-lab-woody commented on src/views/main/index.js
> +import styles from './index.module.css';
어디있죠?

없애주세요.

2023-09-21 09:01 UTC, Yoonkeee commented on src/views/main/index.js
> +import styles from './index.module.css';
삭제했습니다!

2023-09-21 11:50 UTC, f-lab-woody approved these changes
마이너해서 넘어가겠습니다, 추후 고쳐주세요~

2023-09-21 11:50 UTC, f-lab-woody commented on src/views/main/index.js
> +  if (!articleList) return $articleContainer.appendChild(ErrorComponent('articleList load failure'));
nit, return 뒤 다른 로직이 나온다면 한칸은 띄워주세요~

2023-09-21 11:50 UTC, f-lab-woody commented on src/views/main/index.js
> +  const ul = document.createElement('ul');
ul은 line #32 보다 위에서 선언되어야하나요?

2023-09-21 15:17 UTC, merged