feat: models/article.js 내 getArticleBody 로직 수정 및 new line 추가
f-lab-edu/clone-toss-tech pull request #25
Opened 2023-09-23 14:39 UTC by Yoonkeee

## Description

- getArticleBody 함수 내부의 오류를 수정하였습니다.
  - this.getArticleList가 Promise 객체를 반환하는데 [id]로 접근하는 문제가 있었습니다.
  - Promise 객체를 await한 결과값에 [id]로 접근하도록 수정하였습니다.
- getArticleBody 함수 내부의 로직을 읽기 더 쉽게 변경하였습니다.
- one-liner 이후 또다른 로직이 있는 곳에 empty line을 추가하였습니다.

## What type of PR is this?

- [x] 🍕 Feature
- [x] 🐛 Bug Fix
- [x] 🧑‍💻 Code Refactor

## Related Tickets & Documents

[Ticket: WOO-78](https://linear.app/woody-yoonkee/issue/WOO-78/modelsarticlesjs의-getarticlebody에서-오류가-생기는-버그-수정)

2023-09-24 02:33 UTC, f-lab-woody requested changes

2023-09-24 02:33 UTC, f-lab-woody commented on src/models/article.js
>      // TODO: DEV 환경일 때 에러 정보 로그를 출력하는 Util function 추가 예정 Ticket: WOO-75
지워주셔도 되지 않나요?

2023-09-24 02:33 UTC, f-lab-woody commented on src/models/article.js
> +      const head = (await this.getArticleList())[id];
점점 알아보기 힘들어지네요, 좀더 깔끔하게 써볼 수 있을것같아요

2023-09-24 02:33 UTC, f-lab-woody commented on src/models/article.js
> +      const head = (await this.getArticleList())[id];
promise all을 사용하는게 좋을것같아요

2023-09-24 15:48 UTC, Yoonkeee commented on src/models/article.js
>      // TODO: DEV 환경일 때 에러 정보 로그를 출력하는 Util function 추가 예정 Ticket: WOO-75
삭제했습니다.

2023-09-24 15:48 UTC, Yoonkeee commented on src/models/article.js
> +      const head = (await this.getArticleList())[id];
수정하였습니다.

2023-09-25 19:24 UTC, justin-the-developer approved these changes

2023-09-25 19:24 UTC, justin-the-developer commented on src/models/article.js
>      // TODO: DEV 환경일 때 에러 정보 로그를 출력하는 Util function 추가 예정 Ticket: WOO-75
지워주셔도 되지 않나요?

2023-09-25 19:26 UTC, f-lab-woody approved these changes

2023-09-26 02:18 UTC, merged