feat: main 페이지를 담당하는 컨트롤러 생성
f-lab-edu/clone-toss-tech pull request #27
Opened 2023-09-23 15:26 UTC by Yoonkeee

## Description

- 메인 페이지에 관한 로직을 담당하는 컨트롤러입니다.
- 추후 본문 페이지에 관한 로직을 담당하는 컨트롤러(controllers/article.js) 생성 후 index.js에서 두 모듈을 불러와 사용합니다. 

## What type of PR is this?

- [x] 🍕 Feature

## Related Tickets & Documents

[Ticket: WOO-74](https://linear.app/woody-yoonkee/issue/WOO-74/controllers-디렉토리와-메인-페이지-로직을-담당할-mainjs-생성)

2023-09-24 02:45 UTC, f-lab-woody requested changes

2023-09-24 02:45 UTC, f-lab-woody commented on src/controllers/main.js
> +  try {
이 try catch는 렌더 펑션 안으로 들어가야 리젝트된 결과를 캐치블록에서 수거 할수있지 않나요?

2023-09-24 02:45 UTC, f-lab-woody commented on src/controllers/main.js
> +      renderMainPage(await model.getArticleList());
코드가 왜이렇게 보기 어렵죠?

2023-09-24 15:47 UTC, Yoonkeee commented on src/controllers/main.js
> +  try {
위치 이동하였습니다.

2023-09-24 15:48 UTC, Yoonkeee commented on src/controllers/main.js
> +      renderMainPage(await model.getArticleList());
개선하였습니다!

2023-09-25 19:25 UTC, justin-the-developer approved these changes

2023-09-25 19:26 UTC, f-lab-woody approved these changes

2023-09-26 02:19 UTC, merged