feat: app.j에서 class, id 중복되는 부분 변경 (Minor change from PR#22 comment)
f-lab-edu/clone-toss-tech pull request #28
Opened 2023-09-23 15:35 UTC by Yoonkeee

## Description

- [PR#22 Comment](https://github.com/f-lab-edu/clone-toss-tech/pull/22#discussion_r1332287247)에 관한 Minor change입니다.
- app.js에서 class, id로 중복되는 이름 'content'를 중복되지 않게 변경하였습니다.

## What type of PR is this?

- [x] 🍕 Feature

## Related Tickets & Documents

[Ticket: WOO-76](https://linear.app/woody-yoonkee/issue/WOO-76/pr22-comments-todo)

2023-09-24 02:47 UTC, f-lab-woody requested changes

2023-09-24 02:47 UTC, f-lab-woody commented on src/app.js
> +      <div class="content-class" id="content"></div>
제가 말씀드렸던건 왜 아이디와 클래스 둘다 있어야하는지 질문드린겁니다

2023-09-24 15:49 UTC, Yoonkeee commented on src/app.js
> +      <div class="content-class" id="content"></div>
클래스 제거하였습니다.

2023-09-25 19:25 UTC, justin-the-developer approved these changes

2023-09-25 19:27 UTC, f-lab-woody approved these changes

2023-09-26 02:19 UTC, merged