index.html, index.css 생성
f-lab-edu/clone-toss-tech pull request #3
Opened 2023-08-27 07:42 UTC by Yoonkeee

## Description

- index.html과 index.css를 생성했습니다.  
- 기존의 .gitignore에서 src/dev/PseudoCode.js 부분을 삭제하였습니다.

## What type of PR is this?

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Ticket : WOO-15

2023-08-27 15:11 UTC, f-lab-woody requested changes

2023-08-27 15:11 UTC, f-lab-woody commented on src/index.css
> +}
css reset 검색후 적용해주세요

2023-08-27 15:11 UTC, f-lab-woody commented on .gitignore
> -src/dev/PseudoCode.js
해당스콥에 들어있나요?

2023-08-27 15:11 UTC, f-lab-woody commented on index.html
> +</html>
eof

2023-08-27 15:11 UTC, f-lab-woody commented on src/index.css
> +}
eof

2023-08-28 11:00 UTC, Yoonkeee commented on .gitignore
> -src/dev/PseudoCode.js
해당 중복 커밋 제거했습니다.

2023-08-28 11:00 UTC, Yoonkeee commented on src/index.css
> +}
CSS Reset은 추후 따로 티켓 생성 후 Commit&PR 하겠습니다.

2023-08-28 11:01 UTC, Yoonkeee commented on index.html
> +</html>
추가했습니다.

2023-08-28 11:01 UTC, Yoonkeee commented on src/index.css
> +}
추가했습니다.

2023-08-28 15:09 UTC, Yoonkeee commented on src/index.css
> +}
^ index.css에 reset css를 적용하였습니다.

2023-08-28 15:26 UTC, justin-the-developer requested changes

2023-08-28 15:26 UTC, justin-the-developer commented on src/index.css
> +/*! minireset.css v0.0.6 | MIT License | github.com/jgthms/minireset.css */
prettier 사용하시나요?
format설정 적용해주세요~

2023-08-28 15:26 UTC, justin-the-developer commented on index.html
> +<html lang="en">
영어로 작성된것 맞을까요?
아니라면 아래와 같이 수정해주세요
```html
<html lang="ko">
```

2023-08-28 15:26 UTC, justin-the-developer commented on index.html
> +    <title>토스 테크 블로그 클론</title>
nit, 타이틀에 굳이 클론을 넣을필요는 없어보입니다.

2023-08-28 15:46 UTC, Yoonkeee commented on src/index.css
> +/*! minireset.css v0.0.6 | MIT License | github.com/jgthms/minireset.css */
prettier 적용했습니다.

2023-08-28 15:46 UTC, Yoonkeee commented on index.html
> +<html lang="en">
ko로 수정했습니다.

2023-08-28 15:46 UTC, Yoonkeee commented on index.html
> +    <title>토스 테크 블로그 클론</title>
반영하였습니다.

2023-08-28 16:25 UTC, justin-the-developer approved these changes

2023-08-28 16:26 UTC, f-lab-woody approved these changes

2023-08-28 16:27 UTC, merged