chore: 프로젝트의 소개와 로컬 환경 구동을 위한 README.md 수정
f-lab-edu/clone-toss-tech pull request #31
Opened 2023-09-25 16:48 UTC by Yoonkeee

## Description

- README.md를 수정하였습니다.
- 프로젝트를 로컬에서 구동하기 위한 방법을 기재하였습니다.

## What type of PR is this?

- [x] 📦 Chore (Release)

## Related Tickets & Documents

[Ticket: WOO-81](https://linear.app/woody-yoonkee/issue/WOO-81/프로젝트를-로컬에서-실행하기-위한-readmemd-작성)

2023-09-25 19:27 UTC, f-lab-woody approved these changes, later dismissed

2023-09-25 19:27 UTC, f-lab-woody commented on README.md
> +# Toss Tech Blog built with vanilla JS
google docs 링크 첨부해주셔도 좋겠습니다.

2023-09-26 03:04 UTC, Yoonkeee commented on README.md
> +# Toss Tech Blog built with vanilla JS
테크 스펙 링크 추가하였습니다.

2023-09-26 11:14 UTC, f-lab-woody requested changes

2023-09-26 11:14 UTC, f-lab-woody commented on README.md
> +[MVC 패턴](https://developer.mozilla.org/ko/docs/Glossary/MVC)에 기반한 구조로 설계하였습니다.
~구현합니다. (현재)
~설계하였습니다. (과거)

시제를 맞춰주시겠어요?

2023-09-26 11:16 UTC, Yoonkeee commented on README.md
> +[MVC 패턴](https://developer.mozilla.org/ko/docs/Glossary/MVC)에 기반한 구조로 설계하였습니다.
현재 시제로 통일하였습니다.

2023-09-26 12:47 UTC, f-lab-woody approved these changes

2023-09-26 14:31 UTC, merged