feat: 메인 페이지에 적용될 CSS 추가 및 클래스명 변경
f-lab-edu/clone-toss-tech pull request #33
Opened 2023-09-28 13:37 UTC by Yoonkeee

## Description

- 메인 페이지에 CSS를 적용하였습니다.
- Preview는 아래 링크에서 보실 수 있습니다.
[woo-84 preview](http://211.250.82.235:4173/)

## What type of PR is this?

- [x] 🍕 Feature

## Related Tickets & Documents

[Ticket: WOO-84](https://linear.app/woody-yoonkee/issue/WOO-84/메인-페이지에-css-적용)

2023-09-28 15:38 UTC, f-lab-woody requested changes

2023-09-28 15:38 UTC, f-lab-woody commented on src/index.css
> +    margin: 61px auto 200px;
좋아보이지 않습니다.
픽셀 적용하실꺼면 짝수로 지정해주세요.

픽셀이 어떻게 브라우저에서 동작하는지 알아봐주세요

2023-09-28 15:38 UTC, f-lab-woody commented on src/index.css
> +    height: 60%;
이렇게 하시면 추후 이미지 사이즈를 예측하기가어려워집니다

2023-09-28 15:38 UTC, f-lab-woody commented on src/index.css
> +    margin-left: 8%;
왜 마진을 두죠? 컨테이너의 의존시키면 안되나요?

2023-09-28 15:38 UTC, f-lab-woody commented on src/views/main/index.module.css
> +  margin: 72px 10px 0 10px;
타이틀에 마진을 준다기보다는 타이틀을 감쌀 컨테이너에 주시고,
아래에 p태그를 통해서 폰트관련 스타일 가이드 적용해주세요.

2023-09-28 15:38 UTC, f-lab-woody commented on src/views/main/index.module.css
> +  margin-top: 0;
이건 지정해줄필요있나요?

^만약 있다면 reset css에서는 왜 지정이 안되어있었죠?

2023-09-28 15:38 UTC, f-lab-woody commented on src/views/main/index.module.css
> +  color: rgb(128, 128, 128);
왜 rgb를 사용하죠?

2023-09-28 15:38 UTC, f-lab-woody commented on src/views/main/index.module.css
> +  margin-bottom: 12px;
위에 타이틀에 드렸던 코멘트와 동일합니다

2023-09-28 15:38 UTC, f-lab-woody commented on src/views/main/index.module.css
> +  font-size: 15px;
픽셀은 짝수로지정

2023-09-28 15:38 UTC, f-lab-woody commented on src/views/main/index.module.css
> +  color: #4e5968;
여기는 왜 hex code죠?

2023-10-03 14:18 UTC, Yoonkeee commented on src/views/main/index.module.css
> +  color: #4e5968;
위의 rgb를 hex code로 변경하였습니다.

2023-10-03 14:18 UTC, Yoonkeee commented on src/index.css
> +    margin: 61px auto 200px;
수정하였습니다.

2023-10-03 14:18 UTC, Yoonkeee commented on src/index.css
> +    height: 60%;
수정하였습니다.

2023-10-03 14:19 UTC, Yoonkeee commented on src/index.css
> +    margin-left: 8%;
수정하였습니다.

2023-10-03 14:19 UTC, Yoonkeee commented on src/views/main/index.module.css
> +  margin: 72px 10px 0 10px;
수정하였습니다. 헤드 태그이므로 p 대신 h1으로 적용하였습니다.

2023-10-03 14:19 UTC, Yoonkeee commented on src/views/main/index.module.css
> +  margin-top: 0;
삭제하였습니다.

2023-10-03 14:19 UTC, Yoonkeee commented on src/views/main/index.module.css
> +  color: rgb(128, 128, 128);
hex code로 수정하였습니다.

2023-10-03 14:20 UTC, Yoonkeee commented on src/views/main/index.module.css
> +  margin-bottom: 12px;
수정하였습니다.

2023-10-03 14:20 UTC, Yoonkeee commented on src/views/main/index.module.css
> +  font-size: 15px;
수정하였습니다.

2023-10-08 18:47 UTC, f-lab-woody reviewed
질문 몇가지 드렸습니다. 확인해주세요~

2023-10-08 18:47 UTC, f-lab-woody commented on src/index.css
> +    max-width: calc(100% - 48px);
이게 필요한가요?

2023-10-08 18:47 UTC, f-lab-woody commented on src/index.css
> +    max-width: calc(100% - 48px);
width를 92%로 정해두었는데 maxWidth 를 따로 지정해줄필요가 있을까요?

2023-10-08 18:47 UTC, f-lab-woody commented on src/index.css
> +    position: sticky;
포지션 스티키로 할경우 위 콘테이너인 root에도 position relative를 지정해주는게 좋은 습관입니다.
* 다양한 edgecase들을 줄일 수 있어요.

2023-10-09 09:31 UTC, Yoonkeee commented on src/index.css
> +    max-width: calc(100% - 48px);
불필요한 속성이라 삭제했습니다!

2023-10-09 09:32 UTC, Yoonkeee commented on src/index.css
> +    position: sticky;
relative 속성 추가하였습니다.

2023-10-09 12:12 UTC, f-lab-woody approved these changes

2023-10-09 15:46 UTC, merged