App.js 생성
f-lab-edu/clone-toss-tech pull request #4
Opened 2023-08-27 08:07 UTC by Yoonkeee

## Description

App.js를 생성하였습니다.

## What type of PR is this?

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Ticket : WOO-16

2023-08-27 15:14 UTC, f-lab-woody requested changes

2023-08-27 15:14 UTC, f-lab-woody commented on index.html
> +</html>
해당 스콥안에 들어가나요?

2023-08-27 15:14 UTC, f-lab-woody commented on src/index.css
> +}
상동

2023-08-27 15:14 UTC, f-lab-woody commented on src/App.js
> +    <div id="content" style="min-height: calc(100vh - 60px); padding-top: 60px">
inline css는 가급적 사용하지 않는것이 권장사항입니다.

2023-08-27 15:14 UTC, f-lab-woody commented on src/App.js
> +          <img src="images/LogoImage.png" style="max-height: 50px" alt="로고 이미지, 클릭시 메인 페이지로 이동">
alt에 왜 action description이 있을까요?

2023-08-27 15:14 UTC, f-lab-woody commented on src/App.js
> +        <a style="display: flex; align-items: center" href="/">
href="/"말고 다른방법없을까요?

2023-08-27 15:14 UTC, f-lab-woody commented on src/App.js
> +import Requests from './api/Requests.js';
어디있죠? 
디파인되어있지 않은 항목을 왜 import시키나요?

2023-08-27 15:14 UTC, f-lab-woody commented on src/App.js
> +  <section>
섹션이 섹션안에 있나요?

2023-08-28 15:13 UTC, Yoonkeee commented on index.html
> +</html>
revert 했습니다.

2023-08-28 15:13 UTC, Yoonkeee commented on src/index.css
> +}
revert 했습니다.

2023-08-28 15:13 UTC, Yoonkeee commented on src/App.js
> +          <img src="images/LogoImage.png" style="max-height: 50px" alt="로고 이미지, 클릭시 메인 페이지로 이동">
수정하였습니다.

2023-08-28 15:14 UTC, Yoonkeee commented on src/App.js
> +        <a style="display: flex; align-items: center" href="/">
href="/"는 잘못된 방법이었습니다.
해당 부분 변경하였습니다.

2023-08-28 15:14 UTC, Yoonkeee commented on src/App.js
> +import Requests from './api/Requests.js';
수정했습니다.

2023-08-28 15:14 UTC, Yoonkeee commented on src/App.js
> +  <section>
섹션 겹치지 않도록 수정했습니다.

2023-08-28 15:28 UTC, justin-the-developer requested changes

2023-08-28 15:28 UTC, justin-the-developer commented on src/App.js
> +      <div id="content" style="min-height: calc(100vh - 60px); margin: 61px auto 50px;"></div>
inline css

2023-08-28 15:28 UTC, justin-the-developer commented on src/App.js
> +            <img src="images/LogoImage.png" style="max-height: 50px" alt="로고 이미지" />
inline css

2023-08-28 15:28 UTC, justin-the-developer commented on src/App.js
> +app.innerHTML = /* HTML */ `
코멘트를 작성하실땐 코드 위쪽에 넣어주세요~

2023-08-29 08:25 UTC, closed without merging